# Generated by Django 5.2.6 on 2025-10-04 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ChatifyApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='task',
            new_name='post',
        ),
    ]
