# Generated by Django 5.2.6 on 2025-10-07 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatifyApp', '0002_rename_task_comment_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='data',
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
