# Generated by Django 5.2.6 on 2025-10-12 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatifyApp', '0003_remove_comment_comment_remove_comment_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photos',
            field=models.ImageField(blank=True, null=True, upload_to='posts/'),
        ),
    ]
